apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    {{- include "crewmeister.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-mysql-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "crewmeister.mysqlSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crewmeister.mysqlSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}:{{ .Values.mysql.tag }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mysql.storage }}
