{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "crewmeister.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Release.Name }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql-password
      remoteRef:
        key: {{ .Values.externalSecrets.secretName }}
        property: mysql-root-password
{{- end }}
