{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "crewmeister.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
{{- end }}
