{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-app
  labels:
    {{- include "crewmeister.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "crewmeister.appSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
{{- end }}
