apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    {{- include "crewmeister.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "crewmeister.appSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crewmeister.appSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-app
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Release.Name }}-mysql-0.{{ .Release.Name }}-mysql-headless {{ .Values.mysql.port }}; do
                echo "waiting for MySQL...";
                sleep 2;
              done;
              echo "MySQL is ready"
      containers:
        - name: app
          image: {{ .Values.app.image }}:{{ .Values.app.tag }}
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: mysql-password
          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.liveness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.app.probes.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.readiness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.app.probes.readiness.timeoutSeconds }}
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
